import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import SidebarNav from '../../components/SidebarNav'
// ✅ Import getFromCache
import { listServices, createService, updateService, deleteService, getFromCache } from '../../api/client'
import '../../styles/dashboard.css'

export default function Services() {
  const { id } = useParams()
  
  // 🚀 INSTANT LOAD: Initialize state from cache
  const [services, setServices] = useState(() => {
    // The key must match the URL generated by listServices(id, 100, 0)
    const cached = getFromCache(`/services/?business_id=${id}&limit=100&offset=0`)
    return Array.isArray(cached) ? cached : []
  })

  const [form, setForm] = useState({ name: '', description: '', price: '', service_type: 'restaurant' })
  const [editing, setEditing] = useState(null)

  // 🚀 REVALIDATE: Fetch fresh data in background
  useEffect(() => {
    refresh()
  }, [id])

  async function refresh() {
    try {
      const data = await listServices(id, 100, 0)
      setServices(data)
    } catch (err) {
      console.error(err)
    }
  }

  async function onCreate(e) {
    e.preventDefault()
    try {
      await createService({ business_id: id, ...form, price: Number(form.price) })
      setForm({ name: '', description: '', price: '', service_type: 'restaurant' })
      refresh()
    } catch (err) {
      console.error(err)
    }
  }

  async function onUpdate(serviceId) {
    try {
      await updateService(serviceId, { ...form, price: Number(form.price) })
      setEditing(null)
      refresh()
    } catch (err) {
      console.error(err)
    }
  }

  async function onDelete(serviceId) {
    try {
      await deleteService(serviceId)
      refresh()
    } catch (err) {
      console.error(err)
    }
  }

  return (
    <div className="dashboard-page">
      <div className="dashboard-sidebar">
        <SidebarNav />
      </div>
      <div className="dashboard-content">
        <h2 className="page-title">Services</h2>

        {services.length === 0 ? (
          <p>No services listed.</p>
        ) : (
          services.map(s => (
            <div key={s.service_id} className="panel">
              {editing === s.service_id ? (
                <>
                  <input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Service Name" />
                  <textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Description" />
                  <input type="number" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} placeholder="Price" />
                  <div style={{ marginTop: '10px' }}>
                    <button onClick={() => onUpdate(s.service_id)}>Save</button>
                    <button className="ghost" onClick={() => setEditing(null)}>Cancel</button>
                  </div>
                </>
              ) : (
                <>
                  <strong>{s.name}</strong>
                  <p>{s.description}</p>
                  <p>₹{s.price}</p>
                  <div style={{ marginTop: '8px' }}>
                    <button className="ghost" onClick={() => { setEditing(s.service_id); setForm(s) }}>Edit</button>
                    <button className="ghost" onClick={() => onDelete(s.service_id)}>Delete</button>
                  </div>
                </>
              )}
            </div>
          ))
        )}

        <div className="form-body" style={{ marginTop: '20px' }}>
          <h3>Add New Service</h3>
          <form onSubmit={onCreate}>
            <input
              placeholder="Service name"
              value={form.name}
              onChange={e => setForm({ ...form, name: e.target.value })}
            />
            <textarea
              placeholder="Description"
              value={form.description}
              onChange={e => setForm({ ...form, description: e.target.value })}
            />
            <input
              type="number"
              placeholder="Price"
              value={form.price}
              onChange={e => setForm({ ...form, price: e.target.value })}
            />
            
            <button type="submit">Create Service</button>
          </form>
        </div>
      </div>
    </div>
  )
}